
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PagosWSRemote", targetNamespace = "http://webService/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PagosWSRemote {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.Caja
     */
    @WebMethod
    @WebResult(partName = "return")
    public Caja buscarCaja(
        @WebParam(name = "arg0", partName = "arg0")
        Object arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.Factura
     */
    @WebMethod
    @WebResult(partName = "return")
    public Factura buscarFactura(
        @WebParam(name = "arg0", partName = "arg0")
        Object arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String guardarPagos(
        @WebParam(name = "arg0", partName = "arg0")
        PagoArray arg0);

}
