
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PagosWsService", targetNamespace = "http://webService/", wsdlLocation = "http://127.0.0.1:8080/TPFinal-EJB/PagosWs?wsdl")
public class PagosWsService
    extends Service
{

    private final static URL PAGOSWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservice.PagosWsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservice.PagosWsService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/TPFinal-EJB/PagosWs?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/TPFinal-EJB/PagosWs?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PAGOSWSSERVICE_WSDL_LOCATION = url;
    }

    public PagosWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagosWsService() {
        super(PAGOSWSSERVICE_WSDL_LOCATION, new QName("http://webService/", "PagosWsService"));
    }

    /**
     * 
     * @return
     *     returns PagosWSRemote
     */
    @WebEndpoint(name = "PagosWsPort")
    public PagosWSRemote getPagosWsPort() {
        return super.getPort(new QName("http://webService/", "PagosWsPort"), PagosWSRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagosWSRemote
     */
    @WebEndpoint(name = "PagosWsPort")
    public PagosWSRemote getPagosWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webService/", "PagosWsPort"), PagosWSRemote.class, features);
    }

}
